name: Despliegue Ojo de Sauron

on:
  push:
    branches: [ main ]  # Se activa cada vez que subís algo a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v6

      - name: Ejecutar comandos en el servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SERVIDOR_KEY_GITHUB }}
          script: |
            set -euo pipefail # Salir inmediatamente si un comando falla
            echo "Iniciando ejecución de comandos en el servidor..."
            cd /opt/ojo-de-sauron
            echo "¡Conexión exitosa desde GitHub Actions!"
            docker --version
            # Acá iremos agregando los comandos de Docker más adelante
